"""Auto-generated icon manifest. Do not edit manually.

This file is generated by download_icons.py. If this file contains only
AVAILABLE_ICONS = None, the manifest has not been generated yet and the
app will fall back to directory scanning.
"""

# This will be overwritten by download_icons.py when icons are downloaded
AVAILABLE_ICONS = None




