name: Build and Release

on:
    push:
        tags:
            - "v*" # This triggers the workflow for tags that start with 'v'
    workflow_dispatch:

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.x"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  pip install pyinstaller

            - name: Build with PyInstaller
              run: |
                  pyinstaller --onefile --windowed --icon=resources/spoon.png main.py
              shell: bash

            - name: Upload artifact
              uses: actions/upload-artifact@v2
              with:
                  name: ${{ matrix.os }}-build
                  path: dist/

    release:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Download Ubuntu artifact
              uses: actions/download-artifact@v2
              with:
                  name: ubuntu-latest-build

            - name: Download macOS artifact
              uses: actions/download-artifact@v2
              with:
                  name: macos-latest-build

            - name: Download Windows artifact
              uses: actions/download-artifact@v2
              with:
                  name: windows-latest-build

            - name: Create Release
              uses: softprops/action-gh-release@v1
              with:
                  files: dist/*
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
